Repository threshold-network/tbtc-v2, pull requests merged in 2022-02, with the labels that each got.

#110 Bank.approveBalanceAndCall
  solidity/contracts/bank/Bank.sol
  solidity/contracts/bridge/Bridge.sol
  solidity/contracts/vault/IVault.sol
  solidity/contracts/vault/TBTCVault.sol
  solidity/test/bank/Bank.test.ts
  solidity/test/vault/TBTCVault.test.ts
Labels: :chains: solidity

#113 RFC 1: Max BTC Fee Revamped
  docs/rfc/rfc-1.adoc
Labels: 🔬 research

#96 Assemble sweep transaction btc
  tbtc-ts/src/deposit.ts
  tbtc-ts/src/index.ts
  tbtc-ts/src/sweep.ts
  tbtc-ts/test/data/deposit.ts
  tbtc-ts/test/data/sweep.ts
  tbtc-ts/test/deposit.test.ts
  tbtc-ts/test/sweep.test.ts
  tbtc-ts/test/utils/mock-bitcoin-client.ts
Labels: :electric_plug: typescript

#106 Implement sweep function (option 2)
  solidity/contracts/bridge/BitcoinTx.sol
  solidity/contracts/bridge/Bridge.sol
  solidity/contracts/test/TestRelay.sol
  solidity/package.json
  solidity/test/bridge/Bridge.test.ts
  solidity/test/data/sweep.ts
  solidity/yarn.lock
Labels: :chains: solidity

#130 Define `dkg` parameter as non-governable
  docs/rfc/rfc-1.adoc
Labels: 🔬 research

#115 RFC 6: Transaction incentives
  docs/rfc/rfc-6.adoc
Labels: 🔬 research

#126 Sweep gas optimisation
  solidity/contracts/bridge/Bridge.sol
  solidity/hardhat.config.ts
Labels: :chains: solidity

#125 RFC 1: Align RFC 1 Transaction Incentives With RFC 6
  docs/rfc/rfc-1.adoc
Labels: 🔬 research

#132 RFC 1: Spec out details of redemption
  docs/rfc/rfc-1.adoc
Labels: 🔬 research

#135 RFC 1: Redesigning fraud proofs
  docs/rfc/rfc-1.adoc
Labels: 🔬 research
