Repository threshold-network/tbtc-v2, pull requests merged in 2023-03, with the labels that each got.

#525 tBTC v1 sunsetting: VendingMachineV2 and VendingMachineV3
  solidity/contracts/bridge/VendingMachineV2.sol
  solidity/contracts/bridge/VendingMachineV3.sol
  solidity/deploy/24_transfer_tbtc_ownership.ts
  solidity/deploy/30_deploy_vending_machine_v2.ts
  solidity/deploy/31_deploy_vending_machine_v3.ts
  solidity/deploy/32_transfer_vending_machine_v2_ownership.ts
  solidity/deploy/33_transfer_vending_machine_v3_ownership.ts
  solidity/hardhat.config.ts
  solidity/test/bridge/VendingMachine.Upgrade.test.ts
  solidity/test/bridge/VendingMachine.test.ts
  solidity/test/bridge/VendingMachineV2.test.ts
  solidity/test/bridge/VendingMachineV3.test.ts
  solidity/test/integration/utils/fixture.ts
  solidity/test/vault/TBTCVault.OptimisticMinting.test.ts
  solidity/test/vault/TBTCVault.Redemption.test.ts
Labels: :chains: solidity

#563 Expose DKG events getters
  typescript/src/chain.ts
  typescript/src/ethereum.ts
  typescript/src/index.ts
  typescript/src/wallet.ts
  typescript/test/utils/mock-bridge.ts
Labels: :electric_plug: typescript

#567 Monitor DKG lifecycle
  monitoring/docs/monitoring-and-telemetry.adoc
  monitoring/src/wallet-monitor.ts
  monitoring/yarn.lock
Labels: :electric_plug: typescript

#560 Monitor TBTC token total supply
  monitoring/docs/monitoring-and-telemetry.adoc
  monitoring/src/contracts.ts
  monitoring/src/file-persistence.ts
  monitoring/src/index.ts
  monitoring/src/supply-monitor.ts
Labels: :electric_plug: typescript

#542 RFC 8: Cross-chain Tokenized Threshold BTC
  docs/rfc/rfc-8.adoc
Labels: 🔬 research

#571 RFC-7: Updates to the values of timeouts and benchmarks
  docs/rfc/rfc-7.adoc
Labels: 🔬 research

#573 Typescript: Start version 1.2.0-dev
  typescript/package.json
Labels: :electric_plug: typescript

#570 L2WormholeGateway: send and receive tokens
  solidity/contracts/l2/L2WormholeGateway.sol
  solidity/contracts/test/WormholeBridgeStub.sol
  solidity/test/l2/L2WormholeGateway.test.ts
Labels: :chains: solidity

#554 Cross chain arbitrum module
  .github/workflows/cross-chain-arbitrum.yml
  .pre-commit-config.yaml
  .prettierignore
  README.adoc
  cross-chain/arbitrum/.eslintignore
  cross-chain/arbitrum/.eslintrc
  cross-chain/arbitrum/.gitignore
  cross-chain/arbitrum/.mocharc.json
  cross-chain/arbitrum/.prettierignore
  cross-chain/arbitrum/.prettierrc.js
  cross-chain/arbitrum/.solhint.json
  cross-chain/arbitrum/.solhintignore
  cross-chain/arbitrum/.tsconfig-eslint.json
  cross-chain/arbitrum/README.adoc
  cross-chain/arbitrum/contracts/test/ArbitrumTBTCUpgraded.sol
  cross-chain/arbitrum/contracts/test/ArbitrumWormholeGatewayUpgraded.sol
  cross-chain/arbitrum/deploy_l2/00_resolve_arbitrum_token_bridge.ts
  cross-chain/arbitrum/deploy_l2/00_resolve_arbitrum_wormhole_tbtc.ts
  cross-chain/arbitrum/deploy_l2/01_deploy_arbitrum_tbtc_token.ts
  cross-chain/arbitrum/deploy_l2/02_deploy_arbitrum_wormhole_gateway.ts
  cross-chain/arbitrum/deploy_l2/11_authorize_wormhole_gateway_as_minter.ts
  cross-chain/arbitrum/deploy_l2/12_update_wormhole_gateway_mapping.ts
  cross-chain/arbitrum/deploy_l2/21_transfer_arbitrum_tbtc_ownership.ts
  cross-chain/arbitrum/deploy_l2/22_transfer_arbitrum_wormhole_gateway_ownership.ts
  cross-chain/arbitrum/deploy_l2/23_transfer_proxy_admin_ownership.ts
  cross-chain/arbitrum/external/arbitrumGoerli/ArbitrumTokenBridge.json
  cross-chain/arbitrum/external/arbitrumGoerli/ArbitrumWormholeTBTC.json
  cross-chain/arbitrum/external/arbitrumOne/ArbitrumTokenBridge.json
  cross-chain/arbitrum/external/arbitrumOne/ArbitrumWormholeTBTC.json
  cross-chain/arbitrum/external/goerli/TokenBridge.json
  cross-chain/arbitrum/external/mainnet/TokenBridge.json
  cross-chain/arbitrum/hardhat.config.ts
  cross-chain/arbitrum/package.json
  cross-chain/arbitrum/scripts/prepare-artifacts.sh
  cross-chain/arbitrum/slither.config.json
  cross-chain/arbitrum/test/ArbitrumTBTC.Upgrade.test.ts
  cross-chain/arbitrum/test/ArbitrumWormholeGateway.Upgrade.test.ts
  cross-chain/arbitrum/tsconfig.export.json
  cross-chain/arbitrum/tsconfig.json
  cross-chain/arbitrum/yarn.lock
Labels: :chains: solidity
