Repository threshold-network/tbtc-v2, pull requests merged in 2023-06, with the labels that each got.

#631 Update dependencies to `random-beacon`, `ecdsa` and `tbtc-v2`
  solidity/yarn.lock
Labels: :shipit: deployment

#636 Update dependencies to `keep-ecdsa` and `tbtc-v2` packages
  typescript/yarn.lock
Labels: :shipit: deployment

#633 Redemptions prototype: On-chain coordination
  solidity/contracts/bridge/WalletCoordinator.sol
  solidity/test/bridge/WalletCoordinator.test.ts
Labels: :chains: solidity

#584 Publish contracts documentation to GitBook
  .github/workflows/contracts-docs.yml
  solidity/.prettierignore
  solidity/docgen-templates/common.hbs
  solidity/hardhat.config.ts
  solidity/package.json
  solidity/yarn.lock
Labels: :book: documentation

#639 Make `buildRedemptionKey` function static
  typescript/src/ethereum.ts
Labels: :electric_plug: typescript

#640 Split contracts API doc into multiple files
  .github/workflows/contracts-docs.yml
  solidity/hardhat.config.ts
Labels: :book: documentation
